// <auto-generated />
using System;
using MediSync.Prescription.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediSync.Prescription.Infrastructure.Migrations
{
    [DbContext(typeof(PrescriptionDbContext))]
    [Migration("20260802051146_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediSync.Prescription.Domain.Aggregates.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PrescribedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_Prescriptions_DoctorId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Prescriptions_PatientId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Prescriptions_Status");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("MediSync.Prescription.Domain.Aggregates.Prescription", b =>
                {
                    b.OwnsOne("MediSync.Prescription.Domain.ValueObjects.DosageInstruction", "Dosage", b1 =>
                        {
                            b1.Property<Guid>("PrescriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DurationDays")
                                .HasColumnType("int")
                                .HasColumnName("DurationDays");

                            b1.Property<string>("Frequency")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("Frequency");

                            b1.Property<string>("Route")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("RouteOfAdministration");

                            b1.Property<string>("SpecialInstructions")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("SpecialInstructions");

                            b1.HasKey("PrescriptionId");

                            b1.ToTable("Prescriptions");

                            b1.WithOwner()
                                .HasForeignKey("PrescriptionId");
                        });

                    b.OwnsOne("MediSync.Prescription.Domain.ValueObjects.DrugInfo", "Drug", b1 =>
                        {
                            b1.Property<Guid>("PrescriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Dosage")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Dosage");

                            b1.Property<string>("DrugName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("DrugName");

                            b1.Property<string>("GenericName")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("GenericName");

                            b1.HasKey("PrescriptionId");

                            b1.ToTable("Prescriptions");

                            b1.WithOwner()
                                .HasForeignKey("PrescriptionId");
                        });

                    b.Navigation("Dosage")
                        .IsRequired();

                    b.Navigation("Drug")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
